# Generated by Django 4.2 on 2023-07-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('L', 'Laptop'), ('P', 'MobilePhone'), ('H', 'Headphone'), ('K', 'Keyboard'), ('M', 'Mouse')], max_length=2),
        ),
    ]
